language: node_js
sudo: false
node_js:
  - "4"
  - "6"
  - "7"
  - "8"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm

  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux

  - mkdir ~/.tedious
  - >
    echo '{
      "config": {
        "server": "localhost",
        "userName": "sa",
        "password": "yourStrong(!)Password",
        "options": {
          "port": 1433,
          "database": "master"
        }
      }
    }' > ~/.tedious/test-connection.json

before_script:
  - npm prune

script:
  - npm run test
  - TEDIOUS_TDS_VERSION=7_4   npm run test-integration
  - TEDIOUS_TDS_VERSION=7_3_B npm run test-integration
  - TEDIOUS_TDS_VERSION=7_3_A npm run test-integration
  - TEDIOUS_TDS_VERSION=7_2   npm run test-integration
  - TEDIOUS_TDS_VERSION=7_1   npm run test-integration

jobs:
  include:
    - stage: release
      node_js: 7
      before_install: skip
      before_script: skip
      script: npm run semantic-release || true
